### ISSUE TITLE
[backen] Error500 on API request

### ISSUE THREAD

**Issue by manfred-ackermann** [RindusIoTJam/dooropener-Rpi0-#19]
When no web window has opened an API request produces Error500:

```
Feb 24 04:01:12 raspberrypi python[1843]: ERROR:tornado.application:Uncaught exception GET /api/open/a2b2d85f-a895-4143-aa52-980429d0acf8 (192.168.0.108)
Feb 24 04:01:12 raspberrypi python[1843]: HTTPServerRequest(protocol='http', host='192.168.0.105', method='GET', uri='/api/open/a2b2d85f-a895-4143-aa52-980429d0acf8', version='HTTP/1.1', remote_ip='192.168.0.108')
Feb 24 04:01:12 raspberrypi python[1843]: Traceback (most recent call last):
Feb 24 04:01:12 raspberrypi python[1843]: File "/usr/local/doorpi-agent/venv/local/lib/python2.7/site-packages/tornado/web.py", line 1590, in _execute
Feb 24 04:01:12 raspberrypi python[1843]: result = method(*self.path_args, **self.path_kwargs)
Feb 24 04:01:12 raspberrypi python[1843]: File "doorpi.py", line 135, in get
Feb 24 04:01:12 raspberrypi python[1843]: DoorSocketHandler.door.on()
Feb 24 04:01:12 raspberrypi python[1843]: AttributeError: 'NoneType' object has no attribute 'on'
Feb 24 04:01:12 raspberrypi python[1843]: ERROR:tornado.access:500 GET /api/open/a2b2d85f-a895-4143-aa52-980429d0acf8 (192.168.0.108) 48.80ms
```

Move door(ring/open) setup from DoorSocketHandler to Application.

**Comment by manfred-ackermann** [comment]
Fixed with commit e30a9447f2c43101e1d32ec08fdee5361104c695
